fauna:
  - packages/fauna/**/*

dynamodb:
  - packages/dynamodb/**/*

prisma:
  - packages/prisma/**/*
  - packages/prisma-legacy/**/*

typeorm:
  - packages/typeorm-legacy/**/*

firebase:
  - packages/firebase/**/*

pouchdb:
  - packages/pouchdb/**/*

sequelize:
  - packages/sequelize/**/*

documentation:
  - ./**/*.md

tests:
  - jest.config.js
  - packages/**/tests/*
